services:
  sign-turk:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./model_assets:/app/model_assets
      - ./dataset/landmarks:/app/dataset/landmarks
    environment:
      - TF_CPP_MIN_LOG_LEVEL=3
    env_file:
      - path: .env
        required: false
    restart: unless-stopped
